# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(default='Dublin', max_length=64)),
            ],
        ),
    ]
