# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180327_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.Restaurant'),
        ),
    ]
